In [4]:
## Q No. 1 :
import pandas as pd
from sklearn.datasets import load_iris

In [5]:
dataset=load_iris()

In [6]:
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [4]:
X=df.iloc[:,:]
y=dataset.target

In [5]:
X,y

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 array([0, 0, 0, 0, 0, 0,

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [7]:
from sklearn.neighbors import KNeighborsClassifier

In [8]:
classifier=KNeighborsClassifier(n_neighbors=5,p=2,algorithm="auto")

In [9]:
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [10]:
y_pred=classifier.predict(X_test)

In [11]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [13]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[19  0  0]
 [ 0 15  1]
 [ 0  0 15]]
0.98
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      0.94      0.97        16
           2       0.94      1.00      0.97        15

    accuracy                           0.98        50
   macro avg       0.98      0.98      0.98        50
weighted avg       0.98      0.98      0.98        50



In [30]:
## Q no. 2 :

# boston dataset has been removed and alternate dataset is california housing dataset
from sklearn.datasets import fetch_california_housing
dataset=fetch_california_housing()
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [36]:
X=df.iloc[:,:-1]
y=df["Longitude"]

In [37]:
X,y

(       MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude
 0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88
 1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86
 2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85
 3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85
 4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85
 ...       ...       ...       ...        ...         ...       ...       ...
 20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48
 20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49
 20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43
 20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43
 20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37
 
 [20640 rows x 7 columns],
 0       -122.23
 1       -122.22
 

In [38]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [39]:
from sklearn.neighbors import KNeighborsRegressor

In [40]:
regressor=KNeighborsRegressor(n_neighbors=5,algorithm="auto",p=2)

In [41]:
regressor.fit(X_train,y_train)

KNeighborsRegressor()

In [42]:
y_pred=regressor.predict(X_test)

In [43]:
y_pred

array([-118.774, -118.438, -119.886, ..., -119.792, -118.366, -119.714])

In [44]:
from sklearn.metrics import  r2_score,mean_squared_error,mean_absolute_error

In [45]:
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.45067948783024625
1.151063123899002
2.1971159101585434


In [50]:
## Q No. 3 :
from sklearn.datasets import load_iris
dataset=load_iris()
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [51]:
X=df.iloc[:,:]
y=dataset.target
X,y

(     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
 0                  5.1               3.5                1.4               0.2
 1                  4.9               3.0                1.4               0.2
 2                  4.7               3.2                1.3               0.2
 3                  4.6               3.1                1.5               0.2
 4                  5.0               3.6                1.4               0.2
 ..                 ...               ...                ...               ...
 145                6.7               3.0                5.2               2.3
 146                6.3               2.5                5.0               1.9
 147                6.5               3.0                5.2               2.0
 148                6.2               3.4                5.4               2.3
 149                5.9               3.0                5.1               1.8
 
 [150 rows x 4 columns],
 array([0, 0, 0, 0, 0, 0,

In [52]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [53]:
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier()

In [54]:
classifier.fit(X_train,y_train)

KNeighborsClassifier()

In [55]:
y_pred=classifier.predict(X_test)

In [56]:
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [72]:
parameter={"n_neighbors":[i for i in range(0,10)],"p":[2],"algorithm":["auto"]}

In [73]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=classifier,param_grid=parameter,cv=5)

In [74]:
grid

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto'],
                         'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
                         'p': [2]})

In [75]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto'],
                         'n_neighbors': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
                         'p': [2]})

In [77]:
y_pred=grid.predict(X_test)
y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [78]:
grid.best_params_

{'algorithm': 'auto', 'n_neighbors': 1, 'p': 2}

In [7]:
## Q No. 4 :
# boston dataset has been removed and alternate dataset is california housing dataset
from sklearn.datasets import fetch_california_housing
dataset=fetch_california_housing()
df=pd.DataFrame(dataset.data,columns=dataset.feature_names)
df.head()
X=df.iloc[:,:-1]
y=df["Longitude"]

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit_transform(X_train,y_train)

array([[-1.52169954, -0.75868455, -0.91813082, ..., -0.61496167,
        -0.04014979, -0.78315293],
       [ 0.18205382,  0.3523991 ,  0.30748451, ..., -0.36282305,
        -0.05943619,  0.8475975 ],
       [-0.17232772,  1.06666717, -0.25107784, ..., -0.33752194,
         0.09515433, -0.87218816],
       ...,
       [-0.49518065,  0.59048846, -0.59192622, ...,  0.28366387,
         0.01608523, -0.75972261],
       [ 0.96816708, -1.07613702,  0.39144665, ...,  0.30198536,
         0.0039722 ,  0.90383028],
       [-0.68377427,  1.86029835, -0.83041358, ...,  1.03658993,
        -0.08065717,  0.9928655 ]])

In [10]:
from sklearn.neighbors import KNeighborsRegressor

In [11]:
regressor=KNeighborsRegressor(n_neighbors=5,algorithm="auto",p=2)

In [12]:
regressor.fit(X_train,y_train)

KNeighborsRegressor()

In [13]:
y_pred=regressor.predict(X_test)
y_pred

array([-118.774, -118.438, -119.886, ..., -119.792, -118.366, -119.714])

In [18]:
## Q No. 5 :
# Load the Sklearn IRIS dataset
"""
iris = datasets.load_iris()
X = iris.data
y = iris.target
#
# Create train and test split
#
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
#
# Create a pipeline
#
pipeline = make_pipeline(StandardScaler(), KNeighborsClassifier())
#
# Create the parameter grid
#
param_grid = [{
    'kneighborsclassifier__n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10],
    'kneighborsclassifier__p': [1, 2],
    'kneighborsclassifier__weights': ['uniform', 'distance'],
    'kneighborsclassifier__algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
}]
#
# Create a grid search instance
#
gs = GridSearchCV(pipeline, param_grid = param_grid,
                  scoring='accuracy',
                  refit=True,
                  cv=10,
                  verbose=1,
                  n_jobs=2)
#
# Fit the most optimal model
#
gs.fit(X_train, y_train)
#
# Print the best model parameters and scores
#
print('Best Score: %.3f' % gs.best_score_, '\nBest Parameters: ', gs.best_params_)
#
# Print the model score for test data
#
print('Score: %.3f' % gs.score(X_test, y_test))
"""

"\niris = datasets.load_iris()\nX = iris.data\ny = iris.target\n#\n# Create train and test split\n#\nX_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)\n#\n# Create a pipeline\n#\npipeline = make_pipeline(StandardScaler(), KNeighborsClassifier())\n#\n# Create the parameter grid\n#\nparam_grid = [{\n    'kneighborsclassifier__n_neighbors': [2, 3, 4, 5, 6, 7, 8, 9, 10],\n    'kneighborsclassifier__p': [1, 2],\n    'kneighborsclassifier__weights': ['uniform', 'distance'],\n    'kneighborsclassifier__algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],\n}]\n#\n# Create a grid search instance\n#\ngs = GridSearchCV(pipeline, param_grid = param_grid,\n                  scoring='accuracy',\n                  refit=True,\n                  cv=10,\n                  verbose=1,\n                  n_jobs=2)\n#\n# Fit the most optimal model\n#\ngs.fit(X_train, y_train)\n#\n# Print the best model parameters and scores\n#\nprint('Best Score: %.3f' 

In [19]:
## Q No. 6 :
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
#
# Load the Sklearn IRIS dataset
#
iris = datasets.load_iris()
X = iris.data
y = iris.target
#
# Create train and test split
#
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
#
# Feature Scaling using StandardScaler
#
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_test_std = sc.transform(X_test)
#
# Fit the model
#
knn = KNeighborsClassifier(n_neighbors=5, p=2, weights='uniform', algorithm='auto')
knn.fit(X_train_std, y_train)

KNeighborsClassifier()

In [20]:
## Q No. 7 :
#using Formula
# Import NumPy Library
import numpy as np

# initializing points in numpy arrays

P1 = np.array((9, 16, 25))
P2 = np.array((1, 4, 9))

# subtracting both the vectors

temp = P1 - P2

# Using Formula

euclid_dist = np.sqrt(np.dot(temp.T, temp))

# printing Euclidean distance
print(euclid_dist)



21.540659228538015


In [23]:
## Q No. 8 :
# Calculating Manhattan Distance from Scratch in Python
def manhattan_distance(point1, point2):
    distance = 0
    for x1, x2 in zip(point1, point2):
        difference = x2 - x1
        absolute_difference = abs(difference)
        distance += absolute_difference

    return distance